#!/bin/bash

while IFS=: read -r username _ _ _ _ home_directory _; do
    # Print the username and home directory
    echo "User: $username, Home Directory: $home_directory"
done < /etc/passwd | sort -t: -k1,1
